import type { PdfLayout } from "./types";

export const LAYOUT_DEFAULT: PdfLayout = {
  pageWidth: 595,
  pageHeight: 842,
  marginTop: 40,
  marginRight: 40,
  marginBottom: 40,
  marginLeft: 40,
  fontFamily: "Helvetica",
  fontSizeBase: 11,
  blocchi: [
    {
      id: "titolo",
      tipo: "testo",
      x: 40,
      y: 40,
      width: 515,
      height: 30,
      fontSize: 24,
      align: "left",
      visible: true,
      fontWeight: "bold",
      testo: "Fattura n. {{fattura.numero}}",
    },
    {
      id: "info-fattura",
      tipo: "testo",
      x: 40,
      y: 78,
      width: 515,
      height: 40,
      fontSize: 12,
      align: "left",
      visible: true,
      testo:
        "Data: {{fattura.data}}\nMesi di riferimento: {{fattura.mesi}}",
    },
    {
      id: "mittente",
      tipo: "mittente",
      x: 40,
      y: 130,
      width: 250,
      height: 120,
      fontSize: 12,
      align: "left",
      visible: true,
      testo:
        "Mittente\n{{mittente.titoloNomeCognomeSpec}}\n{{mittente.via}}\n{{mittente.cittaProvincia}}\nCF: {{mittente.cf}}\nP.IVA: {{mittente.pIva}}",
    },
    {
      id: "intestatario",
      tipo: "intestatario",
      x: 305,
      y: 130,
      width: 250,
      height: 110,
      fontSize: 12,
      align: "left",
      visible: true,
      testo:
        "Intestatario fattura (Pagante)\n{{intestatario.cognomeNome}}\n{{intestatario.via}}\n{{intestatario.capCitta}}\nCF: {{intestatario.cf}}\nP.IVA: {{intestatario.piva}}",
    },
    {
      id: "paziente",
      tipo: "paziente",
      x: 40,
      y: 260,
      width: 515,
      height: 50,
      fontSize: 12,
      align: "left",
      visible: true,
      testo: "Paziente\n{{paziente.cognomeNome}}",
    },
    {
      id: "dettagli-pagamento",
      tipo: "pagamento",
      x: 40,
      y: 330,
      width: 515,
      height: 130,
      fontSize: 12,
      align: "left",
      visible: true,
      testo:
        "Dettagli pagamento\nImporto totale:    {{fattura.prezzoTotale}}\nModalità:    {{fattura.modalitaPagamento}}\nN. sedute:    {{fattura.sedute}}\nNote:    {{fattura.commento}}",
    },
    {
      id: "dettaglio-mesi",
      tipo: "mesi",
      x: 40,
      y: 470,
      width: 515,
      height: 80,
      fontSize: 12,
      align: "left",
      visible: true,
      meseConfig: {
        titolo: "Dettaglio mesi",
        descrizioneTemplate: "{{riga.meseLabel}}",
        valoreTemplate: "{{riga.prezzo}}",
        mostraTotale: true,
        totaleLabel: "Totale",
      },
    },
    {
      id: "totale",
      tipo: "testo",
      x: 40,
      y: 580,
      width: 515,
      height: 25,
      fontSize: 14,
      align: "left",
      visible: true,
      fontWeight: "bold",
      testo: "Totale fattura: {{fattura.prezzoTotale}}",
    },
  ],
};

export const DEFAULT_BLOCCO: Pick<
  PdfLayout["blocchi"][number],
  "width" | "height" | "fontSize" | "align" | "visible"
> = {
  width: 200,
  height: 60,
  fontSize: 12,
  align: "left",
  visible: true,
};
